import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar/Navbar'
import Footer from '@/components/Footer/Footer'
import {Toaster} from 'react-hot-toast'
import Provider from '@/context/authContext'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Wrong Opinions | Home',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider id='provider-container'>
            <Navbar/>
            {children}
            <Toaster 
              id='toast-container'
              position="top-center"
              gutter={12}
              />
            <Footer/>
        </Provider>
      </body>
    </html>
  )
}
